version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing frontend dependencies...
      - cd frontend
      - npm install

  build:
    commands:
      - echo Building React app...
      - npm run build

  post_build:
    commands:
      - echo Deploying build to S3...
      - aws s3 cp build/ s3://cicdbucket/ --recursive

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
